### ISSUE TITLE
[BUG] 2.4.12 Containers reporting 2.4.11 version

### ISSUE THREAD

**Issue by KALRONG** [dfir-iris/iris-web#573]
**Describe the bug**
While updating from 2.4.11 to 2.4.12 I noticed serveral things:

- Instructions may be outdated as still ask for docker build while it does nothing.
- Even changing to v.2.4.12 docker-compose.yaml was pointing to 2.4.11 images
- Zip file on the releases section also points to 2.4.11
- After doing a simply git pull, checking that 2.4.12 was configured, fire everything up, app still shows as version 2.4.11 and no signs of the published changes, looks like the docker images where not updated.

**To Reproduce**
1. Try to update the application from 2.4.11 to 2.4.12 as of 29/08/2024

**Expected behavior**
Images to be on 2.4.12.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser: Chrome

**Comment by whikernel** [comment]
Hi! 

Indeed somehow the tag wasn't on the right commit. I just corrected, the new images should be available in the next few minutes.  
For the documentation, we already removed the `docker compose build` and replaced by pull: https://docs.dfir-iris.org/latest/operations/upgrades/#upgrading

**Comment by KALRONG** [comment]
Thanks for the quick response :) Sorry I was referring to the one in the readme of the repository, I will try the new instructions then.

**Comment by KALRONG** [comment]
Just tried the new procedure, all steps, and still seeing 2.4.11 and no trace of the new seika module so I understand that the images are still the same.

**Comment by whikernel** [comment]
That is weird. The images are up to date, I tested and it works as expected. 
Can you run the following and show the output?
```
git checkout v2.4.12
docker compose pull 
docker images | grep "iris"
```

**Comment by KALRONG** [comment]
For some reason my git wasn't propertly switching to 2.4.12 so de docker-compose.yaml was still pointing to 2.4.11, deleted the folder, cloned again and now Im finally on 2.4.12!

Still can't see the Seika module under Manage - Advance - Modules, not sure if I missed a dependency or it should be already there

**Comment by whikernel** [comment]
Nice!
It's preinstalled but not registered. Do `Add module` and then write `iris_seika_module`, it will add it.

**Comment by KALRONG** [comment]
> Nice! It's preinstalled but not registered. Do `Add module` and then write `iris_seika_module`, it will add it.

Will try it, Im gonna close the issue as the problem is solved, thanks a lot!
